### ISSUE TITLE
[FYI] `wassima` is now available from ArchLinux User Repository as `python-wassima-git`

### ISSUE THREAD

**Issue by kseistrup** [jawah/wassima#4]
[ This is an informational message only. No action is required on your part, and the issue can be closed at your discretion. ]

I thought you'd like to know that ArchLinux users can now install `wassima` directly from ArchLinux User Repository (AUR) as `python-wassima-git`:

+ https://aur.archlinux.org/packages/python-wassima-git

The package can be installed using an [AUR helper](https://wiki.archlinux.org/title/AUR_helpers), e.g. `yay`:

```sh
» yay -S python-wassima-git
```

This will build the python module from the latest commit, and install it along with the README and the LICENSE.

:pray:

**Comment by Ousret** [comment]
Dully noted. Thank you.
