### ISSUE TITLE
inconsistent package metadata at version 1.1.3

### ISSUE THREAD

**Issue by dimbleby** [jawah/wassima#8]
some distributions of wassima 1.1.3 have the requirement
```
certifi; (platform_python_implementation != "CPython" or python_full_version < "3.7.10") or (platform_system != "Darwin" and platform_system != "Windows" and platform_system != "Linux") or (platform_machine != "x86_64" and platform_machine != "s390x" and platform_machine != "aarch64" and platform_machine != "armv7l" and platform_machine != "ppc64le" and platform_machine != "ppc64" and platform_machine != "AMD64" and platform_machine != "arm64" and platform_machine != "ARM64" and platform_machine != "i686") or (platform_python_implementation == "PyPy" and python_version >= "3.11")
```
while others do not

eg https://files.pythonhosted.org/packages/03/8b/9f6c3f0c2c3eb9cbad3019e5534075b97145ea55c003ab307e6ea3317c3e/wassima-1.1.3-py3-none-any.whl does but https://files.pythonhosted.org/packages/1e/5b/1cdcb0b6469f0a728587e9882cb2bed2cf595bcf4ac2093d103d461f8024/wassima-1.1.3-cp37-abi3-macosx_10_12_x86_64.whl does not

while this is allowed by python packaging it makes life difficult for projects that produce cross-platform lockfiles such as `uv` and `poetry` - which set of requirements should they follow in building that cross-platform solution?

it would be particularly ironic if https://github.com/python-poetry/poetry/pull/9685 turned poetry into a project for which poetry could not build a cross-platform lockfile!

**Comment by Ousret** [comment]
Of course, this makes sense.
Anything that can make our integrator life easier, we'll do.

It is fixed and will be published as 1.1.4
